### ISSUE TITLE
Request for Transitive Module builds in mixed_static_framework

### ISSUE THREAD

**Issue by asa** [line/rules_apple_line#13]
Testing with transitive modules does not work for simple cases extending //examples/ios/Mixed with a single transitive module.  A working example would be great.

**Comment by thii** [comment]
@asa Could you elaborate a little more details?

**Comment by asa** [comment]
Probably best to give you an example Pr. Basically there is an issue with the static linking of transitive dependancies.  I would like to get a fully static final framework that imported all of the contents of several dependent modules(some swift, some objc) into a single, distributable framework.  I could not use the new avoid_deps=[] to get this to work.

**Comment by asa** [comment]
I submitted a pr for this example. Let me know what it takes to get this submodule compiled into the framework.  Thanks!

**Comment by thii** [comment]
Resolved by https://github.com/line/rules_apple_line/pull/14.
