### ISSUE TITLE
Missing #import <Module/Module.h> file in generated Module-Swift.h

### ISSUE THREAD

**Issue by tinder-maxwellelliott** [line/rules_apple_line#21]
Hello There!

I am seeing the following error when I am compiling a mixed framework target:

```
bazel-out/apl-ios_x86_64-fastbuild/bin/Projects/Module/Module/Module-Swift.h:223:9: fatal error: 'Module/Module.h' file not found
#import <Module/Module.h>
```

This is happening in the code generated -Swift header

When I search through my `bazel-out` directory I cannot find `Module.h`. What is the right way to go about debugging this issue

**Comment by tinder-maxwellelliott** [comment]
It appears running my bazel command without `--incompatible_objc_compile_info_migration` allows `Module.h` to be created as expected

**Comment by thii** [comment]
Ah yeah, I forgot to mention in the README but `--incompatible_objc_compile_info_migration` is required if you want to use the latest rules_apple and rules_swift.

**Comment by tinder-maxwellelliott** [comment]
I can update the readme to reflect this change
