### ISSUE TITLE
Header map generation not working

### ISSUE THREAD

**Issue by michaeleisel** [line/rules_apple_line#26]
Maybe this should be an issue in rules_ios, I'm not sure, but I'll start here. Header maps don't seem to be working for me. The `copts` added seem correct, but the .hmap files don't seem to get created during the build. Trying to build `zz` here fails with it being unable to find a header for `"yo.h"`.

BUILD.bazel:
```
load("@rules_apple_line//apple:apple_library.bzl", "apple_library")

apple_library(
    name = "zz",
    srcs = ["a.swift", "a.m", "nest/yo.h"],
)
```

a.m:
```
#import "yo.h"

void a() {}
```

nest/yo.h and a.swift: empty files

If I add the headermaps to the `data` attr, I can sort of get it working for non-sandboxed builds, but overall I'm not sure what's going on here. I'm on Bazel 3.7.0

**Comment by thii** [comment]
There's some outdated implementation here. I'll try to upstream our internal one.
