### ISSUE TITLE
`mixed_static_framework` fail to import generated -Swift.h file.

### ISSUE THREAD

**Issue by muizidn** [line/rules_apple_line#31]
Hello!

I have an issue when trying to use `mixed_static_framework` to be used with https://github.com/mxcl/PromiseKit

## Layout
```shell
.
├── PromiseKit
│   └── BUILD
└── WORKSPACE
```
## Build

```python
load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")
load("@rules_apple_line//apple:mixed_static_framework.bzl", "mixed_static_framework")
load("@rules_apple_line//apple:objc_library.bzl", "objc_library")

# Using Mixed Static Framework

mixed_static_framework(
    name = "PromiseKit",
    module_name = "PromiseKit",
    srcs = glob([
        "Sources/**/*.m",
        "Sources/**/*.swift",
    ]),
    hdrs = glob([
        "Sources/**/*.h",
    ]),
    objc_copts = [
        "-Ibazel-out/apl-darwin_x86_64-dbg/bin/PromiseKit",  # i expect this is wrong
        "-IPromiseKit/Sources"
    ],
)
```

Building with `bazel build //PromiseKit` throws these errors

```shell
Use --sandbox_debug to see verbose messages from the sandbox
PromiseKit/Sources/AnyPromise.m:4:13: error: 'PromiseKit/PromiseKit-Swift.h' file not found with <angled> include; use "quotes" instead
    #import <PromiseKit/PromiseKit-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            "PromiseKit/PromiseKit-Swift.h"
PromiseKit/Sources/AnyPromise.m:6:9: fatal error: 'PMKCallVariadicBlock.m' file not found
#import "PMKCallVariadicBlock.m"
        ^~~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.
Target //PromiseKit:PromiseKit failed to build
INFO: Elapsed time: 8.808s, Critical Path: 8.57s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```
Ideally this should works since -Swift.h file is generated (inside bazel-out). As for importing `.m` file I've got suggestion to add search header path but still doesn't work or I am understand it wrong.

**Comment by omarzl** [comment]
I think that -iquote and -I flags only apply to header search files, I couldn't find a flag that works for importing implementation files, that is a quite strange thing to do from PromiseKit, I achieve to compile it by disabling sandbox this way:

`build //:PromiseKitFramework  --spawn_strategy=local`

But of course you lose sandboxing feature.

Here are some docs I found:

https://stackoverflow.com/questions/4916646/difference-between-file-h-and-file-h-import-statements
https://gcc.gnu.org/onlinedocs/gcc/Directory-Options.html

I tried with the some other gcc flags as specified in the last doc but couldn't make it work

**Comment by muizidn** [comment]
@omarzl  Thank you. Just know about this sandbox disabling feature. I think this is my misunderstanding. For header imports, I can make workaround by `aspect`. But for importing implementation file, it is uncommon and I can fork the project to fix it.

**Comment by muizidn** [comment]
I think I will close this issue until future case says otherwise.
