### ISSUE TITLE
Best way to suppress INFO logs from `swiftgen` rule

### ISSUE THREAD

**Issue by tinder-maxwellelliott** [line/rules_apple_line#38]
Hello!

I am running into an issue where I get a lot of logs from SwiftGen, is there any way to remove these INFO logs but keep my other info logs? Thanks

```terminal
INFO: From SwiftGen Projects/Modules/Domain/AModuleLocalized.swift
File written: bazel-out/ios-x86_64-min12-applebin_ios-ios_x86_64-fastbuild-ST-c928d317f2e9/bin/Projects/Modules/AModuleLocalized.swift
```

**Comment by thii** [comment]
I filed an issue for it a while ago here https://github.com/SwiftGen/SwiftGen/issues/823.

Another way is creating a wrapper that invokes swiftgen and filters the output.

**Comment by tinder-maxwellelliott** [comment]
Thanks for the quick response!

**Comment by tinder-maxwellelliott** [comment]
> I filed an issue for it a while ago here [SwiftGen/SwiftGen#823](https://github.com/SwiftGen/SwiftGen/issues/823).
> 
> Another way is creating a wrapper that invokes swiftgen and filters the output.

Do you do this in your codebase? Do you have a simple Genrule for this?

**Comment by thii** [comment]
No, it's still in my TODOs :)
