### ISSUE TITLE
How to include header search path for metal_library rule

### ISSUE THREAD

**Issue by vikage** [line/rules_apple_line#39]
Hi LINE developer.
I use your rules to build metal_library. But i can't find any way to include header when build.
I use metal_library that import "MTIShaderLib.h" in MetalPetal lib.
Please provide the way to import header

**Comment by thii** [comment]
Can you provide an example (that builds with Xcode)?

**Comment by vikage** [comment]
[DemoCompileMetal.zip](https://github.com/line/rules_apple_line/files/6798419/DemoCompileMetal.zip)
@thii Here is example that I can build with Xcode.
